# Generated by Django 5.2 on 2025-04-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Renault', 'Renault'), ('Peugeot', 'Peugeot'), ('Opel', 'Opel'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia')], max_length=15)),
                ('model', models.CharField(max_length=20)),
                ('year', models.DateField()),
                ('plate_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
