# Generated by Django 5.2 on 2025-04-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_client_alter_car_price_per_day_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='days_number',
        ),
        migrations.AddField(
            model_name='rental',
            name='days',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
