# Generated by Django 5.2 on 2025-04-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_rental_days_number_rental_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
