# Generated by Django 5.2 on 2025-04-24 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rental_price_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Renault', 'Renault'), ('Peugeot', 'Peugeot'), ('Opel', 'Opel'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia')], max_length=15)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.carmodel'),
        ),
    ]
