# Generated by Django 5.2 on 2025-05-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_carmodel_alter_car_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='name',
            new_name='model_name',
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
