# Generated by Django 5.2 on 2025-05-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_rename_name_carmodel_model_name_alter_rental_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rental.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.brand'),
        ),
    ]
