# Generated by Django 5.2 on 2025-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_brand_remove_carmodel_brand_carmodel_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
