# Generated by Django 5.2 on 2025-05-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_remove_rental_status_alter_car_status_alter_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
