# Generated by Django 5.2 on 2025-05-05 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_rename_brand_name_brand_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='car/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cin',
            field=models.ImageField(upload_to='client/cin/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='driver_licence',
            field=models.ImageField(upload_to='client/licence/'),
        ),
    ]
