# Generated by Django 5.2 on 2025-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_car_created_at_client_created_at_rental_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
