# Generated by Django 5.2 on 2025-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_alter_brand_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(default='', upload_to='models/'),
        ),
    ]
