# Generated by Django 5.2 on 2025-05-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_carmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='', upload_to='car/'),
        ),
    ]
