# Generated by Django 5.2 on 2025-05-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_alter_car_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='', upload_to='cars/'),
        ),
    ]
