# Generated by Django 5.2 on 2025-05-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_remove_carmodel_image_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
