# Generated by Django 5.2 on 2025-05-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_client_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
