# Generated by Django 5.2 on 2025-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_remove_client_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField>', editable=False, max_length=50, unique=True),
        ),
    ]
