# Generated by Django 5.2 on 2025-05-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_client_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cin',
            field=models.ImageField(upload_to='clients/cin/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='driver_licence',
            field=models.ImageField(upload_to='clients/licence/'),
        ),
    ]
