# Generated by Django 5.2 on 2025-05-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_alter_client_cin_alter_client_driver_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
    ]
