# Generated by Django 5.2 on 2025-05-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_remove_client_full_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'cin'), name='unique_client'),
        ),
    ]
