# Generated by Django 5.2 on 2025-05-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_client_unique_client'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_client'),
        ),
    ]
